const fs = require('fs');
const path = require('path');

// A minimal valid PDF file base64 encoded
const pdfBase64 = "JVBERi0xLjQKJcOkw7zDtsO0CjEgMCBvYmogPDwvVHlwZSAvQ2F0YWxvZyAvUGFnZXMgMiAwIFIgPj4KZW5kb2JqCjIgMCBvYmogPDwvVHlwZSAvUGFnZXMgL0tpZHMgWzMgMCBSXSAvQ291bnQgMSA+PgplbmRvYmoKMyAwIG9iaiA8PC9UeXBlIC9QYWdlIC9QYXJlbnQgMiAwIFIgL1Jlc291cmNlcyA0IDAgUiAvTWVkaWFCb3ggWzAgMCA1OTUuMjggODQxLjg5XSAvQ29udGVudHMgNiAwIFIgPj4KZW5kb2JqCjQgMCBvYmogPDwvRm9udCA8PC9GMSA1IDAgUiA+PiA+PgplbmRvYmoKNSAwIG9iaiA8PC9UeXBlIC9Gb250IC9TdWJ0eXBlIC9UeXBlMSAvQmFzZUZvbnQgL0hlbHZldGljYSA+PgplbmRvYmoKNiAwIG9iaiA8PC9MZW5ndGggNDQgPj4Kc3RyZWFtCkJUCjcwIDc1MCBUZAovRjEgMjQgVGYKKER1bW15IFBERiBmaWxlIGZvciB0ZXN0aW5nKSBUagpFVAplbmRzdHJlYW0KZW5kb2JqCnhyZWYKMCA3CjAwMDAwMDAwMDAgNjU1MzUgZiAKMDAwMDAwMDAxNSAwMDAwMCBuIAowMDAwMDAwMDYxIDAwMDAwIG4gCjAwMDAwMDAxMjIgMDAwMDAgbiAKMDAwMDAwMDIyNiAwMDAwMCBuIAowMDAwMDAwMjY5IDAwMDAwIG4gCjAwMDAwMDAzNTYgMDAwMDAgbiAKdHJhaWxlcgo8PC9TaXplIDcgL1Jvb3QgMSAwIFIgPj4Kc3RhcnR4cmVmCjQ1MAolJUVPRgo=";

const pdfBuffer = Buffer.from(pdfBase64, 'base64');
const targetPath = path.join(__dirname, 'public', 'pdfs', 'test.pdf');

fs.writeFileSync(targetPath, pdfBuffer);
console.log('test.pdf created at', targetPath);
